### ISSUE TITLE
Hitting tab rapidly in succession causes tabs to be inserted

### ISSUE THREAD

**Issue by Qix-** [dthree/wat#8]
Title sounds weird, but auto-completion isn't a smooth as it could be. When you hit tab multiple times, the tabs flood the console. Some of them are compensated for, but most of the time they get put in there. It seems `wat` is handling them correctly, but cosmetically it makes it look all weird.

**Comment by dthree** [comment]
Just to clarify, do you mean that after the second tab, if nothing changed, I should make it refrain from redrawing?

I can absolutely do this, but I designed autocompletion to exactly mirror linux-style autocompletion.

On a linux terminal, type `ls` and then repeatedly hit tab. It does, from what I can see, the exact same thing.

Unless I'm totally misduplicating you?

**Comment by Qix-** [comment]
I mean when I hit tab multiple times in succession, wat doesn't re-draw like it should. I would show an example but wat errored out (posting a new issue :dancer:)

**Comment by dthree** [comment]
Hmm. Yeah, if you could show an example, because I can't seem to reproduce that.

**Comment by Qix-** [comment]
<img width="244" alt="screen shot 2015-08-21 at 12 56 27 pm" src="https://cloud.githubusercontent.com/assets/885648/9416638/0ef09222-4804-11e5-9b7d-8560c8ed13cc.png">

Note the cursor position. This is after hitting tab 3 times. Wat performs correctly - suggesting possible results - but the cursor still advances.

**Comment by dthree** [comment]
Haha funky. What TTY pgm is that?

**Comment by Qix-** [comment]
iTerm2 + Zsh. Should be fairly standard.

**Comment by dthree** [comment]
Okay got it.

Can you do a big favor in debugging this:

`npm install vantage -g`
`$ vantage`

Can you check if it's doing it in the above too? I need to find out whether it's a Vantage or wat problem. Thanks.!

**Comment by Qix-** [comment]
Hitting tab in vantage just makes tab characters.
<img width="458" alt="screen shot 2015-08-21 at 7 28 03 pm" src="https://cloud.githubusercontent.com/assets/885648/9421891/c2a7b7b0-483a-11e5-8698-8602d2bda02c.png">

**Comment by dthree** [comment]
Gotcha so it is Vantage. Good i'll fix.

**Comment by dthree** [comment]
@Qix- Upgrade inquirer, which created a million bugs in Vorpal, but I fixed most of them now. As part of this, I think I nailed the tab bug (was able to reproduce it), and so it should be good now.

While I know some other things are broken right now, could you install a fresh copy of Wat and see if your tab thing is fixed?

Thanks!

**Comment by Qix-** [comment]
Definitely not fixed unfortunately.

<img width="461" alt="screen shot 2015-08-30 at 4 44 00 pm" src="https://cloud.githubusercontent.com/assets/885648/9569877/5babf08c-4f36-11e5-9f39-4ca227e348fd.png">

**Comment by dthree** [comment]
Okay... just did another Vorpal update. Could you please try this again?

if it still isn't working, your terminal isn't inserting tabs, but something else (maybe multiple spaces?).

What I do now is listen in on keypresses and remove trailing `tab` characters right after insertion, so if you're still getting it, they aren't tabs.

**Comment by Qix-** [comment]
Seems to be fixed :)

**Comment by Qix-** [comment]
```
? node

  Fetching node...
/Users/qix/.nvm/versions/node/v4.0.0/lib/node_modules/wat [ { name: 'docs',
    error:
     { [Error: ENOENT: no such file or directory, lstat '/Users/qix/.nvm/versions/node/v4.0.0/lib/node_modules/wat/docs']
       errno: -2,
       code: 'ENOENT',
       syscall: 'lstat',
       path: '/Users/qix/.nvm/versions/node/v4.0.0/lib/node_modules/wat/docs' } } ]
/Users/qix/.nvm/versions/node/v4.0.0/lib/node_modules/wat/dist/clerk/indexer.js:162
      throw new Error(root);
      ^

Error: /Users/qix/.nvm/versions/node/v4.0.0/lib/node_modules/wat
    at Walker.<anonymous> (/Users/qix/.nvm/versions/node/v4.0.0/lib/node_modules/wat/dist/clerk/indexer.js:162:13)
    at emitThree (events.js:97:13)
    at Walker.emit (events.js:175:7)
    at Walker._wPostFilesHandler (/Users/qix/.nvm/versions/node/v4.0.0/lib/node_modules/wat/node_modules/walk/lib/walk.js:133:10)
    at /Users/qix/.nvm/versions/node/v4.0.0/lib/node_modules/wat/node_modules/walk/node_modules/foreachasync/forEachAsync.js:15:16
    at Array.forEach (native)
    at Walker.next [as _wCurFileCallback] (/Users/qix/.nvm/versions/node/v4.0.0/lib/node_modules/wat/node_modules/walk/node_modules/foreachasync/forEachAsync.js:14:15)
    at Walker._wLstatHandler (/Users/qix/.nvm/versions/node/v4.0.0/lib/node_modules/wat/node_modules/walk/lib/walk.js:83:10)
    at /Users/qix/.nvm/versions/node/v4.0.0/lib/node_modules/wat/node_modules/walk/lib/walk.js:105:12
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Comment by dthree** [comment]
Thanks. Still fine-tuning autodocs. 

But that error's funny. It's on a file walk. Do you not have a /doc directory there?
